### PR TITLE
Fix eslint action

### PR DESCRIPTION
**Pull request by bluquar**
I tried to fix the was deployment as well but there's something wrong with it, I still don't know what. maybe something about the node version.

### CODE REVIEW

**Review by lowellbander — APPROVED** [review]
how did you fix the issue / what was broken? not clear to me from code :/

**Comment by lowellbander** [comment]
I believe this PR has caused #66

**Comment by bluquar** [comment]
Hmm that doesn't explain why the main deployment is broken, because it wasn't even deployed via GitHub.

**Comment by bluquar** [comment]
The eslint action wasn't completing it successfully. There were some lint warnings and also it was using the wrong caching strategy (npm instead of yarn)

**Pull request merged**
