### PR TITLE
[v0.2.0] Fix Android; Require login on client; Implement email allowlist

### PR DESCRIPTION
**Pull request by bluquar**
# Fix Android

Crash on launch fixed by changes to `src/client/aid-app/graphql/GraphQLClientURI.ts`

Blank screens after switching tabs fixed by changes to `src/client/general-purpose/navigation/StackNavigatorInsideTabNavigator.tsx`

https://user-images.githubusercontent.com/4309735/147841847-2c521422-a013-4354-bb02-d61c74c44d50.mov

# Requiring login on client

Note that this only applies to the UI. It isn't enforced for API calls yet.

https://user-images.githubusercontent.com/4309735/147852720-3d46efbc-7a1a-41ec-809a-19ce60c9fb9f.mov

# Allowlist

https://user-images.githubusercontent.com/4309735/147852311-9503da85-a2b7-41ca-8058-f1f8fbf19e5a.mov

### CODE REVIEW

**Comment by lowellbander** [comment]
That middle screen recording load for me in browser or the github app, does it for you?

Also, why so many different changes in a single PR?

**Review by lowellbander — APPROVED** [review]
Super duper lovely! You're so darn quick!!

Ideally I'd like to see that middle screen capture before recording, and load up the android app on my phone, but approving nonetheless!

**Comment by bluquar** [comment]
1. I still don't have a way of doing stacked changes that doesn't involve a lot of manual merging. So that's why there are so many changes in a single PR. My workflow is to always use the chris branch and all the changes I make in between times when you accept my changes all go in a single PR. I think we've discussed this before :)

**Comment by bluquar** [comment]
2. Aw bummer, that middle screen recording is my favorite one! Here it is on Google drive: https://drive.google.com/file/d/14ViBmQSkA4lby7KVnwD95t2aceA7c5m0/view?usp=drivesdk

**Comment by bluquar** [comment]
3. Thanks for saying it's lovely and that I'm quick :)

**Comment by lowellbander** [comment]
Does the manual merging even happen when you're developing on separate
branches? Like branch for PR1, then branch off that for PR2?

**Comment by bluquar** [comment]
It used to, but maybe now that I know about git reset --soft origin/latest it won't. I can make latest -> PR1 -> PR2, and then merge PR1 into latest once it's approved. In the past I would then have to merge latest into PR2 since it was now "ahead", which would require manual merging. But now I could just switch to PR2 and run git reset --soft origin/latest and make a new commit. That way works as long as I'm the only person working on it. But if I'm not, then it undoes changes that anyone else made between the "latest" that I started with and the current "latest."

**Pull request merged**
