### PR TITLE
Fix web deployment and also add iOS deployment metadata

### PR DESCRIPTION
**Pull request by bluquar**
Web deployment: the .env file needs to be created before we build the client JS, since that's how process.env.GRAPHQL_URI gets populated

[chris.dandelion.supplies](http://chris.dandelion.supplies) is working, so I think this fix works :)

### CODE REVIEW

**Comment by lowellbander** [comment]
That Chris deployment isn't loading for me :(

Curiously, it's not a blank screen but is rather taking a very long time to load

**Comment by lowellbander** [comment]
I can't update using the android build, but I'll try deleting mine for a clean install and see if that works

**Comment by lowellbander** [comment]
Fresh install of the android build was successful, UT opening the app flashes a cute dandelion emoji and then crashes

**Review by lowellbander — DISMISSED** [review]
Requesting changes because Chris web deployment and android deployment both fail, which I figure should be blockers for merging. Wyt?

**Comment by bluquar** [comment]
The Chris web deployment works for me. Can you try loading it on your computer and look at the developer tools to see what's going on?

I don't think Android should be a blocker right now since it doesn't work in general yet and getting native apps to work is something I'm actively working on improving right now, but this PR isn't aiming to get Android working.

**Comment by bluquar** [comment]
Removing android-build.yaml and ios-build.yaml for now because I don't expect them to work yet, so they're just distracting/noisy on PRs right now.

**Comment by lowellbander** [comment]
chris.dandelion.supplies loads just fine on my laptop, but still not on my phone. I connected my phone to my computer and followed [these steps](https://developer.chrome.com/docs/devtools/remote-debugging/), but all that gets me is the the network request is stuck at Pending :(

image

**Comment by bluquar** [comment]
Can you try http instead of https?

**Comment by lowellbander** [comment]
OOOO interesting! ya sure!

**Comment by lowellbander** [comment]
chris.dandelion now working for me on mobile web!

**Review by lowellbander — APPROVED** [review]
u fixed it! (?)

**Pull request merged**
